//World Variables
const VIEWPORT_WIDTH = 1920;
const VIEWPORT_HEIGHT = 1080;

const ARENA_WIDTH = 6000;
const ARENA_HEIGHT = 6000;

const STARTING_SPAWN_INTERVAL = 5000;
const MIN_SPAWN_INTERVAL = 4000;
const SPAWN_DECREASE_RATE = 0.98;
const SPAWN_TYPES = ['crawler', 'sprinter', 'spitter'];
const MIN_SPAWN_DISTANCE = 1500;

//Player Variables
const PLAYER_WIDTH = 128;
const PLAYER_HEIGHT = 128;

const PLAYER_SPAWN_X = ARENA_WIDTH / 2 - PLAYER_WIDTH / 2;
const PLAYER_SPAWN_Y = ARENA_HEIGHT / 2 - PLAYER_HEIGHT / 2;

const PLAYER_BASE_SPEED = 12;

const PLAYER_INVUL_TIME = 50;

//Hunter Variables
const HUNTER_SPEED_MODIFIER = 1.1;
const HUNTER_HP = 2;
const HUNTER_RANGE = 1800;
const HUNTER_FIRING_RATE = 75;

const ARROW_WIDTH = 56;
const ARROW_HEIGHT = 56;
const ARROW_SPEED = 108;
const ARROW_PIERCE = 10;
const ARROW_DAMAGE = 30;

//Gunner Variables
const GUNNER_SPEED_MODIFIER = 1.1;
const GUNNER_HP = 3;
const GUNNER_RANGE = 1400;
const GUNNER_FIRING_RATE = 8;

const BULLET_WIDTH = 48;
const BULLET_HEIGHT = 48;
const BULLET_SPEED = 96;
const BULLET_PIERCE = 1;
const BULLET_DAMAGE = 4;

//Enemy Variables
const CRAWLER_PACK_SIZE = 4;
const SPRINTER_PACK_SIZE = 1;
const SPITTER_PACK_SIZE = 2;

//Crawler Variables
const CRAWLER_WIDTH = 96;
const CRAWLER_HEIGHT = 96;

const CRAWLER_BASE_SPEED = 4;

const CRAWLER_BASE_HP = 20;
const CRAWLER_BASE_HP_INCREASE = 0.3;

const CRAWLER_SCORE = 30;

//Sprinter Variables
const SPRINTER_WIDTH = 72;
const SPRINTER_HEIGHT = 72;

const SPRINTER_BASE_SPEED = 10;

const SPRINTER_BASE_HP = 10;
const SPRINTER_BASE_HP_INCREASE = 0.1;

const SPRINTER_SCORE = 120;

//Spitter Variables
const SPITTER_WIDTH = 96;
const SPITTER_HEIGHT = 96;

const SPITTER_BASE_SPEED = 4;

const SPITTER_BASE_HP = 10;
const SPITTER_BASE_HP_INCREASE = 0.1;

const SPITTER_SCORE = 60;

const SPITTER_RANGE = 700;

const SPIT_WIDTH = 48;
const SPIT_HEIGHT = 48;
const SPIT_SPEED = 24;

//Misc Variables